version: 2.1
jobs:
  create_image:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: gcloud config
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            curl -L -o /tmp/docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-<< parameters.docker_ver >>.tgz
            tar -xz -C /tmp -f /tmp/docker.tgz
            echo "export PATH=/tmp/docker:$PATH" >> $BASH_ENV

workflows:
  build:
    jobs:
      - create_image
