language: ruby
cache: bundler
sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: "ruby-head"

before_install:
  - gem i bundler -v 1.8.4

script:
  - bundle exec rake

